FROM golang:1.24 AS builder
ARG GOPROXY=direct
WORKDIR /go/src/ehang.io/nps
COPY . .
RUN go mod edit -go=$(go version | awk '{print $3}' | sed 's/go//') && \
    go mod tidy && \
    go get -d -v ./...
RUN CGO_ENABLED=0 go build -ldflags="-w -s -extldflags -static" ./cmd/npc/npc.go
RUN mkdir tmp

FROM scratch
COPY --from=builder /go/src/ehang.io/nps/npc /
COPY --from=builder /go/src/ehang.io/nps/tmp /tmp
VOLUME /conf
ENTRYPOINT ["/npc"]
